# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/RescureNet
spring.datasource.username=postgres
spring.datasource.password=123456

# ===============================
# = JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
jwt.signerKey=R3WCR9EDLLJSWqNOdxcX5lAMMOlmZEBM4Hf6h1lDZpdxjYUZRyTrQNHJxk1CVYLRksHCpjtOTfslbVLwCQMVdwFcz5FoTPDAP6yaxZkWtdLB5xxcTo7YQSoGpcSxN7Sdqr
server.port=8080
server.servlet.context-path=/identity
app.services.profile=http://localhost:8888/api/v1/profile
jwt.valid-duration:6000
jwt.refreshable-duration: 12000

# ===============================
# = EMAIL CONFIGURATION
# ===============================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:pn8382853@gmail.com}
spring.mail.password=${MAIL_PASSWORD:equsnycwajtagbfv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST:smtp.gmail.com}
spring.mail.properties.mail.debug=true
logging.level.com.example.demo.service.EmailService=DEBUG
logging.level.org.springframework.mail=DEBUG
# ===============================
# = KAFKA CONFIGURATION
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=userRegistered:com.rescuenet.events.UserRegisteredEvent
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

# Application name for correlation
spring.application.name=auth-service

